config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#index'
  resources :users, only: [:edit, :update, :index, :show]
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }

  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


 before_action :configure_permitted_parameters, if: :devise_controller?

 def set_current_user
  @current_user = User.find_by(id: session[:user.id])
 end

 def autheniticate_user
  if @current_user == nil
   redirect_to(new_user_session_path)
  end
 end
 


 def after_sign_in_path_for(resources)
  user_path(current_user.id)
 end

 def after_sign_out_path_for(resources)
  root_path
 end

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id


    if @book.save

      redirect_to book_path(@book), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user

      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new

  end

  def show
    @booker = Book.find(params[:id])
    @books = Book.all
    @user = @booker.user
    @book = Book.new
  end


  def edit
    @booker = Book.find(params[:id])
    if @booker.user != current_user
      redirect_to books_path
    end
  end

  def update
    @booker = Book.find(params[:id])
    if @booker.update(book_params)
      redirect_to book_path(@booker), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end



  def destroy
    booker = Book.find(params[:id])
    booker.destroy
    redirect_to books_path
  end



  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def different_user
    unless user_signed_in? == current_user.id
      redirect_to edit_user_path(current_user.id)
    end
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def index
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end





  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>

  <p id="notice"></p>
  <div class="container">
    <div class="row">

      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        
        <% if @booker.errors.any? %>
          <div id="error_explanation">
  
            <h2><%= @booker.errors.count %> errors prohibited this book from being saved: </h2>
  
            <ul>
              <% @booker.errors.full_messages_for(:title).each do |message| %>
                <li><%= message %></li>
              <% end %>
  
              <% @booker.errors.full_messages_for(:body).each do |message| %>
                <li><%= message%></li>
              <% end %>
            </ul>
  
          </div>
        <% end %>


        <%= form_with model:@booker, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
        <% end %>

        <%= link_to 'Show', book_path(@booker) %>
        |
        <%= link_to 'Back', books_path %>
      </div>
    </div>

  </div>
</main>

<%= render "homes/footer" %>

app/views/books/index.html.erb
<body>


  <p id="notice"></p>

    <div class="container px-5 px-sm-0">

    <% if @book.errors.any? %>
      <div id="error_explanation">

        <h2><%= @book.errors.count %> errors prohibited this book from being saved: </h2>

        <ul>
          <% @book.errors.full_messages_for(:title).each do |message| %>
            <li><%= message %></li>
          <% end %>

          <% @book.errors.full_messages_for(:body).each do |message| %>
            <li><%= message%></li>
          <% end %>
        </ul>

      </div>
    <% end %>
    <div class="row">


      <%= render "users/form", user: @user,  book: @book %>


      <div class="col-md-8 offset-md-1">

        <%= render "users/list", books: @books %>

      </div>
    </div>


  <%= render 'homes/footer' %>
</body>

app/views/books/show.html.erb
<body>




    <main>
      <p id="notice"></p>

      <div class="container">


      <div class="row">
        <%= render "users/form", user: @user,  book:@book %>



        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table">

            <tbody>

              <tr>
                <td>
                  <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size:'40x40' %></br>
                  <%= link_to "#{@user.name}", user_path(@user) %>
                </td>

                <td><%= link_to "#{@booker.title}", book_path(@booker) %></td>

                <td><%= @booker.body %></td>

                <td>
                  <% if @booker.user == current_user %>
                    <%= link_to 'Edit', edit_book_path(@booker), class: "btn btn-sm btn-success" %>
                  <% end %>  
                </td>

                <td>
                  <% if @booker.user == current_user %>
                    <%= link_to 'Destroy', book_path(@booker), method: :delete, "data_confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %>
                  <% end %>
                </td>

              </tr>



            </tbody>
          </table>
        </div>
      </div>
      </div>
    </main>
  <%= render 'homes/footer' %>
</body>

app/views/homes/_header.html.erb
   <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href = "/">
            <span>Bookers</span>
          </a>

          <button class="navbar-toggler">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">


              <% if user_signed_in? %>

                <li class="fas fa-home nav-link text-light">
                 <%= link_to "Home", user_path(current_user.id) %>
                </li>


                <li class="fas fa-users nav-link text-light">
                 <%= link_to "Users", users_path %>
                </li>

                <li class="fas fa-book-open nav-link text-light">
                  <%= link_to "Books", books_path %>
                </li>

                <li class="fas fa-sign-out-alt nav-link text-light">
                 <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                </li>

              <% else %>

                <li class="fas fa-home nav-link text-light">
                 <%= link_to "Home", root_path %>
                </li>

                <li class="fas fa-link nav-link text-light">
                 <%= link_to "About", home_about_path %>
                </li>

                <li class="fas fa-user-plus nav-link text-light">
                  <%= link_to "Sign up", new_user_registration_path %>
                </li>

                <li class="fas fa-sign-in-alt nav-link text-light">
                  <%= link_to "Log in", new_user_session_path %>
                </li>

              <% end %>


            </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/homes/index.html.erb
<p id="notice"></p>
    <div class="container">
      <div class="row">

        <div class="px-3 mx-auto">
          <h1>welcome to
            <i class="fas fa-book"></i>
              <strong>Bookers</strong>
              !!
           </h1>
        </div>
      </div>
    </div>

<%= render 'homes/footer' %>

app/views/homes/top.html.erb
<body>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
           <h1>welcome to
             <i class="fas fa-book"></i>
             <strong>Bookers</strong>
             !!
          </h1>

          <p>In
           <i class="fas fa-book"></i>
          <strong>Bookers</strong>
           ,
          </p>

          <p>you can share and exchange your opinions , inpressions , and emotions</p>
           <p> about various books!</p>
         

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign-in" href="/users/sign_in">Log in</a>
        </div>

        <div class="row">
          <a class="btn btn-success btn-sm btn-block mb-3 sign-up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>




  </div>
  
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href = "/">
            <span>Bookers</span>
          </a>


          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">


              <% if user_signed_in? %>

                <li>
                 <%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>


                <li>
                 <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
                </li>

                <li>
                  <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
                </li>

                <li>
                 <%= link_to " Log out", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
                </li>

              <% else %>

                <li>
                 <%= link_to " Home", root_path, class: "fas fa-home font nav-link text-light" %>
                </li>

                <li>
                 <a class= "fas fa-link nav-link text-light" href="/home/about"> About</a>
                </li>

                <li>
                  <%= link_to " Sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                </li>

                <li>
                  <%= link_to " Log in", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
                </li>

              <% end %>


            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

   <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<div class="col-md-3">
  <h2>User info</h2>

  <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: '63x63' %>

  <table class="table">
    <tbody>

        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>

        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>

    <div class="row">
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>

    <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>

        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>

</div>

app/views/users/_list.html.erb
<div class= "col-md-8 offset-md-1" %>
  <h2>Books</h2>
    <table class="table table-hover tableinverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>

      <tbody>

          <% books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: '40x40' %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>

      </tbody>
    </table>
  </div>

app/views/users/edit.html.erb
<body>

  <main>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>User info</h2>
          <% if @user.errors.any? %>
            <div id="error_explanation">

              <h2><%= @user.errors.count %> errors prohibited this book from being saved: </h2>

              <ul>
                <% @user.errors.full_messages_for(:name).each do |message| %>
                  <li><%= message %></li>
                <% end %>

              </ul>

            </div>
          <% end %>

            <%= form_with model: @user, local:true do |f| %>
              <div class="form-group">
                <label for="user_name">Name</label>
                <%= f.text_field :name %>
              </div>

              <div class="form-group">
                <label for="user_image">Image</label>
                <%= f.attachment_field :profile_image %>
              </div>

              <div class="form-group">
                <label for="user_introduction">Introduction</label>
                <%= f.text_area :introduction %>
              </div>

              <div class="form-group">
                <%= f.submit 'Update User' %>
              </div>
            <% end %>
        </div>
      </div>

    </div>
  </main>
  <%= render 'homes/footer' %>
</body>

app/views/users/index.html.erb
   <%= flash[:notice] %>
   <div class="container px-5 px-sm-0">
      <div class="row">

        <%= render "users/form", user: @user,  book: @book %>




        <div class="col-md-8 offset-md-1">
          <h2>User</h2>
          <table class="table table-hover tableinverse">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th></th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'40x40'  %>
                <th><%= user.name %></th>
                <th><%= link_to 'Show', user_path(user) %></th>
              </tr>
              <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
<%= render "homes/footer" %>

app/views/users/show.html.erb
<body>

    <p id="notice"></p>
    <div class="container px-5 px-sm-0">
      <div class="row">

       <%= render "users/form", user: @user, book: @book %>

        <div class="col-md-8 offset-md-1">

           <%= render "users/list", books: @books %>



        </div>
      </div>
    </div>

  <%= render 'homes/footer' %>
</body>